export const impl = {
  Async: await import("../std/Async.js"),
  Bool: await import("../std/Bool.js"),
  Char: await import("../std/Char.js"),
  Console: await import("../std/Console.js"),
  Err: await import("../std/Err.js"),
  Fs: await import("../std/Fs.js"),
  List: await import("../std/List.js"),
  Math: await import("../std/Math.js"),
  Obj: await import("../std/Obj.js"),
  Panic: await import("../std/Panic.js"),
  Rand: await import("../std/Rand.js"),
  Ref: await import("../std/Ref.js"),
  Re: await import("../std/Re.js"),
  Set: await import("../std/Set.js"),
  Str: await import("../std/Str.js"),
  Table: await import("../std/Table.js"),
  Test: await import("../std/Test.js"),
};
